apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: meu-app
  name: meu-app
  namespace: ak8s-test
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: --type=ClusterIP
  selector:
    app: meu-app
status:
  loadBalancer: {}

